### ISSUE TITLE
Remove "github/workspace" from filename in csv?

### ISSUE THREAD

**Issue by maelle** [urlstechie/urlchecker-python#35]
Not sure if this belongs to the library or action. Would it be possible (and make sense) to have the filename relative to the folder in which the URL checks are run?

**Comment by maelle** [comment]
>  it's most useful to leave the full paths for the print to the screen.

Why? (out of curiosity)

**Comment by vsoch** [comment]
If you imagine someone running the check in one terminal, they very likely want to copy paste the url to quickly load the file somewhere else. With the full path that is easy to do, without it, they have to remember and navigate there first. You can also imagine why it's useful for testing - when we were debugging your issue it would have been a lot harder to do without seeing the full path. Generally, it's providing more information to the user running the tool, and (my 0.02) is that this transparency is usually better.

**Comment by maelle** [comment]
oh right! Thanks!

**Comment by SuperKogito** [comment]
So I think this is a matter of preference. It is not that major, but I think we all agree that having the full file path is better. I personally prefer to see the full path of the files, because it would be much easier to know which file is where. The github/workspace variant is neat but can be confusing for many users :/ So I would say have the full path in? and not just the derived one ... I would rather see something like: `github-repo-name/content/technical/_index.md`.

**Comment by vsoch** [comment]
@maelle we just merged https://github.com/urlstechie/urlchecker-python/pull/36 so after the container is built (it's an automated build) it should be live for the action. Let us know if it works /if you run into any trouble! We won't be releasing this particular version on pypi until we get in @SuperKogito regex work, I still need to review that.

**Comment by maelle** [comment]
thanks! Yes it worked in https://github.com/r-hub/docs/pull/24/checks?check_run_id=588010321
